services:
  # --- База данных (MariaDB) ---
  mariadb:
    image: bitnami/mariadb:latest
    container_name: suitecrm_mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - MARIADB_USER=bn_suitecrm
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - suitecrm_network

  # --- Почтовый сервер (Mailhog) ---
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"   # Web-интерфейс Mailhog: http://localhost:8025
    networks:
      - suitecrm_network

  # --- SuiteCRM ---
  suitecrm:
    image: bitnami/suitecrm:latest
    container_name: suitecrm_app
    depends_on:
      - mariadb
      - mailhog
    environment:
      # --- Параметры БД ---
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami
      - SUITECRM_DATABASE_TYPE=mysql

      # --- Параметры для входа в SuiteCRM ---
      - SUITECRM_USERNAME=user
      - SUITECRM_PASSWORD=bitnami
      - SUITECRM_EMAIL="[email protected]"

      # --- Отключаем автоконфигурацию SMTP ---
      - SUITECRM_SMTP_ENABLE=no

      # Разрешаем пустые пароли — иначе Bitnami может «ругаться»
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - "8080:8080"    # SuiteCRM на http://localhost:8080
    volumes:
      - suitecrm_data:/bitnami/suitecrm
    networks:
      - suitecrm_network

volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local

networks:
  suitecrm_network:
    driver: bridge